[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-Zlinker-features=-lld", "-Ctarget-cpu=cortex-a53"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Zlinker-features=-lld"]
